import hmac

import hashlib

from django.conf import settings


def verify_razorpay_signature(order_id, payment_id, signature):
    """
    Role: The Integrity Check.
    Verifies that the payment proof was actually generated by Razorpay.
    """
    # 1. Create the payload string as defined by Razorpay's protocol
    generated_signature_body = f"{order_id}|{payment_id}"

    # 2. Hash the body using your Secret Key
    expected_signature = hmac.new(
        key=settings.RAZORPAY_KEY_SECRET.encode(),
        msg=generated_signature_body.encode(),
        digestmod=hashlib.sha256
    ).hexdigest()

    # 3. Compare: If they match, the payment is authentic
    return hmac.compare_digest(expected_signature, signature)